### ISSUE TITLE
Add an opportunity to filter all games same way as "on sale" ones

### ISSUE THREAD

**Issue by gt4wow** [SteamDatabase/steamdb.info-issues#626]
[Feature Request]
Please add an opportunity to filter all games same way as "on sale" ones.
For example I want to be able to see all unowned 1$ games that are not Low Confidence Metric
I can easily filter unowned games and exclude Low Confidence Metric ones on Sales tab, for example https://steamdb.info/sales/?min_discount=0&min_rating=0&displayOnly=Game&tagid=-1003823 but there's no way to do this for all games to find out the cheapest unowned games that never go on sale and exclude games that don't give +1's.

**Comment by xPaw** [comment]
With the way sales page currently works, it wouldn't work for _all_ games.

You can use instant search for this: https://steamdb.info/instantsearch/?refinementList%5Btags%5D%5B0%5D=-Profile%20Features%20Limited&refinementList%5BappType%5D%5B0%5D=Game
