### ISSUE TITLE
Add language filter section

### ISSUE THREAD

**Issue by luca2125** [SteamDatabase/steamdb.info-issues#671]
Hi,

is possible add language filter (3 textbox):

1) Game
2) Voice
3) Subtitle

for site:

https://steamdb.info/

thank you !

**Comment by xPaw** [comment]
https://steamdb.info/instantsearch/

Added!

![image](https://user-images.githubusercontent.com/613331/119802327-23116f00-bee7-11eb-8a26-6ac85fc62584.png)

**Comment by luca2125** [comment]
thank you !!

**Comment by albertdick** [comment]
It would be interesting to have these filters in the "sale" section on https://steamdb.info/sale/.
