### ISSUE TITLE
Add SteamChina price

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamdb.info-issues#680]
SteamChina's cc is XC

https://store.steampowered.com/api/appdetails/?appids=736190&cc=xc&filters=price_overview

There is currently no `CN` price for this game. https://store.steampowered.com/api/appdetails/?appids=736190&cc=cn&filters=price_overview

And SteamChina games have a Key "steamchinaapproved".
https://steamdb.info/search/?a=app_keynames&keyname=478

**Comment by xPaw** [comment]
How did you find `xc`?

**Comment by wordlesswind** [comment]
> How did you find `xc`?

Use SteamChina Client's UA to view https://store.steampowered.com

You will find that only "steamchinaapproved" games exist in the list.

UA:
`Mozilla/5.0 (Windows; U; Windows NT 10.0; en-US; Valve Steam Client/steamchina/1596217132; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36`

And
```
<div id="application_config" style="display: none;" data-config="
...
"COUNTRY":"XC"
</div>
```

**Comment by xPaw** [comment]
Do you think it would be safe to request `xc` instead of `cn` for games that are on approved list? Hopefully there shouldn't be different prices.

**Comment by wordlesswind** [comment]
> Do you think it would be safe to request `xc` instead of `cn` for games that are on approved list? Hopefully there shouldn't be different prices.

This is a tangled question. I don’t think the pricing in the `CN` will be different from that in the `XC`.
But nowadays there is a game that is not available in `CN`, but in `XC`.
https://steamdb.info/app/736190/

But my plan is to tell you that SteamChina's cc is `XC`, and other aspects have not been considered so much for the time being.

**Comment by xPaw** [comment]
It will request xc instead of cn for approved apps now.

![image](https://user-images.githubusercontent.com/613331/90125768-3cd43200-dd6b-11ea-9492-721d8012cac9.png)


But, there are apps like 553640 ICEY which can be bought in CN, but not XC...

**Comment by wordlesswind** [comment]
I suspect that the price problems of these apps may be caused by Steam's automated procedures: when I first noticed SteamChina on Tuesday, its currency was US dollars.

So actually SteamChina’s data should be copied in the Steam “US” region.

The evidence is: App [967240](https://steamdb.info/app/967240) packages are divided into [Mainland China](https://steamdb.info/sub/409144/) and [RoW](https://steamdb.info/sub/404613/).
The package released on SteamChina is RoW.

So at this moment we should wait for Valve or the publisher to solve this problem.

**Comment by wordlesswind** [comment]
Now visit https://store.steampowered.com/?cc=xc and https://store.steampowered.com/api/appdetails/?appids=736190&cc=xc&filters=price_overview will return a 400 status code.

Using SteamChina UA, you can access https://store.steampowered.com/ but cannot access the API, and the API returns 404.

**Comment by wordlesswind** [comment]
I forgot this issue...

Now, all apps published on Steam China have prices, which should be the same as Steam Global’s CNY pricing.

There is an exception: [CS:GO Prime Status Upgrade](https://steamdb.info/sub/54029/)
It was published [on Steam China](https://store.steamchina.com/sub/54029/), but did not set CNY price of Steam Global.
