### ISSUE TITLE
Add case-insensitive search for app/package keys

### ISSUE THREAD

**Issue by gh89275** [SteamDatabase/steamdb.info-issues#698]
You don't expect the "LIKE" operator to be case-sensitive:

![Screen Shot 2021-03-28 at 1 00 54 PM](https://user-images.githubusercontent.com/26887375/112740249-15169f00-8fc7-11eb-8bd1-fa2917515e7a.png)

It would sure be nice to have a case-insensitive option.

**Comment by xPaw** [comment]
That indeed would be nice to have.

For now, you can search devs/publisher in instant search: https://steamdb.info/instantsearch/?query=kojima
