### ISSUE TITLE
Timestamps in local timezone

### ISSUE THREAD

**Issue by darkred** [SteamDatabase/steamdb.info-issues#699]
### Feature Description

I believe it would be very useful the timestamps in the site to be converted to local timezone.
_Currently they are in `UTC`_.

For example: in my country it's `UTC+3`(dst).
In my case, a timestamp example: 14:00 would be converted to 17:00.

Thank you

**Comment by xPaw** [comment]
While it is certainly possible, I chose to keep everything UTC a while back for consistently as there are things like date filters and a bunch of other stuff that may be get wonky.

Gonna close this issue because I have no plans on doing this.
