### ISSUE TITLE
Price is wrong for Resident Evil Village

### ISSUE THREAD

**Issue by feaff000** [SteamDatabase/steamdb.info-issues#701]
- _Browser name and version:_ 
- _Device (mobile or desktop):_ 
- _Page where the issue happens:_ 

### Describe the bug

as so many other instances I reported before sometimes the game price is wrong, like Resident Evil Village this time, in this case because the "standard/basic" edition is in a bundled with another game (verse) the game showing for the basic version on your website is $79.99 which is for "Resident Evil Village & Resident Evil 7 Complete Bundle".

**Comment by xPaw** [comment]
This is the price Steam selects, not a bug.

https://store.steampowered.com/search/?term=Resident+Evil+Village
