### ISSUE TITLE
Icon 🌐 in search results

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/steamdb.info-issues#702]
### Suggestion
I'd like to see the store page icon (🌐) also appear in package/app [search](https://steamdb.info/search/) results, just like you can in the app/package tables/tabs of individual app/packages pages (e.g. the DLC section on an app page). 

### Why?
This way you can easily navigate to the store page and also see which apps/packages in your search results have an accessible store page. So, for example you can easily see which apps are delisted or removed from the steam store.

### Concept
![image](https://user-images.githubusercontent.com/4411977/117590015-ddeeee00-b12d-11eb-8f04-e7768c8f7cf4.png)

**Comment by xPaw** [comment]
Added.

**Comment by Revadike** [comment]
Thank you!
