### ISSUE TITLE
Average price per hour inaccurate.

### ISSUE THREAD

**Issue by Mike90909090** [SteamDatabase/steamdb.info-issues#703]
On my profile it says I have an average price/hour of €2.84 but if you take my account worth/hours played on paid games you'd get below €1.00. I have atleast 600 hours on paid games and my account is worth at most €349,  so that would give way below €1.00. I also tried adding up all price/hour on paid games and then dividing by amount of paid games, but that got me to about €1.02 and not €2.84. This also happens for a friend of mine who has about €1300 account value and like 3000 hours on paid games but his average is at €13/hour.

**Comment by xPaw** [comment]
It skips unplayed games.

**Comment by xPaw** [comment]
It sums up prices per hour from each game and divides by that count.
