### ISSUE TITLE
RSS information 

### ISSUE THREAD

**Issue by Natalia-Oreiro** [SteamDatabase/steamdb.info-issues#705]
Hi all,

I really like your project and I would like to present information with the help of RSS.

1, Any game that released out and supports the Linux operating system.

2, All action on games (keep) from: https://steamdb.info/upcoming/free/ 

3, All games that have been released and support Japanese language

(is it possible to set this informations - does it provide any RSS?), thanks.

**Comment by xPaw** [comment]
We don't have such RSS feeds and no plans to add them.

For 1 and 3 you can do advanced filtering here: https://steamdb.info/instantsearch/

For 2, in our Discord we have a channel that announces free promotions.
