### ISSUE TITLE
[Minor] Dark Mode usable breaks some aspect of elements in-use

### ISSUE THREAD

**Issue by slistack** [SteamDatabase/steamdb.info-issues#706]
- _Browser name and version:_ Firefox 89.0, F34.0 (4920) + Safari
- _Device (mobile or desktop):_ Desktop + Iphone SE, 2020, MX9R2ZD/A, iOS 14.6 
- _Page where the issue happens:_ https://steamdb.info

### Describe the bug
When turning Dark Mode feature, certain elements doesn't change intermittent to respective color mode in comparison in-content page.

### Steps to reproduce
1) Switch on/off the UI button
2) Observe

### Expect result
Dark Mode should've sort of effect on all visual elements when browsing that apply dark colors to avoid white flashes.

### Actual result
Such footer & navbar (sidemenu) doesn't change representative their colors upon button switch action.

![steamdbf_dark](https://user-images.githubusercontent.com/85315031/120710419-c9044100-c4c6-11eb-93f4-3a1b3097c2a0.gif)

**Comment by xPaw** [comment]
Looks like whatever you have in your browser is breaking it. Footer and header do not have white themes on steamdb (by design).

**Comment by slistack** [comment]
Aha, so just to be clear. By default, it's on dark theme except the actual button slider is mainly featured to change view for the body content-schemas? It doesn't look to be honest quite responsive for the white theme appeal on my end but that's another for the feature request. IMHO probably way better to stay dark theme for convenience.

Anyhow, thanks for clarification.
