### ISSUE TITLE
Watchlist with the price column?

### ISSUE THREAD

**Issue by sprajagopal** [SteamDatabase/steamdb.info-issues#707]
### Feature Description
I'm not sure if this feature already exists. I thought the watchlist was meant to be a single place to look for price changes. I can't figure out how to add columns to the watchlist. Is there such an option? Such that price changes in particular games can be checked directly?

**Comment by xPaw** [comment]
I added price column to watching page.

**Comment by sprajagopal** [comment]
ok that was way too fast! Thanks!
