### ISSUE TITLE
Add multiple Keys search

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/steamdb.info-issues#708]
### Feature Description

Currently, you can only search one App/Package Key at once. But sometimes you want to search multiple keys. For example, `extended_allowpurchasefromrestrictedcountries ` together with `extended_purchaserestrictedcountries`, which would have helped [this guy](https://www.steamgifts.com/discussion/ct8Gu/steam-is-there-a-website-or-way-to-see-all-the-games-that-are-region-exclusive#vgiV5Pw).
I imagine you can simply extend the SQL query with an `AND` predicate in the backend and create a dynamic form in the frontend, if you are willing to. I don't think it will make queries more expensive to do (I imagine it still has to iterate throw each item once), but if you are concerned with that, you could limit the number of key search filters.

**Comment by xPaw** [comment]
I added a secondary key search that uses equals operator. I think that should help with most such queries for packages.

I can revisit and expand this later based on the usage.
