### ISSUE TITLE
Incorrect sorting on Bundles page

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/steamdb.info-issues#709]
![image](https://user-images.githubusercontent.com/4411977/123446287-05642200-d5d9-11eb-9d8c-3ea0e20dfa4b.png)
seems like text sorting is applied, rather than number sorting

https://steamdb.info/bundles/

**Comment by Revadike** [comment]
Adding `data-sort` should fix it.

**Comment by Js41637** [comment]
Noticing the same thing, the sorting seems to work when the currency is in USD but for me in AUD it also does not work. Clicking the price sort does nothing at all.

![ss (2021-06-30 at 09 41 26)](https://user-images.githubusercontent.com/6258213/123881179-83347e80-d987-11eb-898d-dbe48f157f96.gif)

**Comment by Revadike** [comment]
Can confirm:
https://steamdb.info/bundles/?cc=au

**Comment by Revadike** [comment]
Thanks @xPaw <3
