### ISSUE TITLE
Hide bundles with no discount

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/steamdb.info-issues#713]
### Feature Description
https://steamdb.info/bundles/

![image](https://user-images.githubusercontent.com/4411977/123447665-67715700-d5da-11eb-82a0-5cacfa3f3dc9.png)

I don't care about bundles that provide no benefit in terms of discount.

**Comment by xPaw** [comment]
I've just hidden bundles with no base discount from that page entirely, seems pointless.

**Comment by Revadike** [comment]
Exactly
