### ISSUE TITLE
Improve free packages even more

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/steamdb.info-issues#716]
### Feature Description

I know, I know... just something to think about.

 1. Add countdown after being rate limited
 2. Add ability to retrieve new free-on-demand packages since the initial page load

For 2, you probably need some endpoint that can retrieve these new packages since a certain date. However, that will likely get abused... Alternatively, you could perform a hard page refresh and use some URL query parameters.

**Comment by xPaw** [comment]
No
