### ISSUE TITLE
Use baselines in local currency for products by cost list

### ISSUE THREAD

**Issue by Nixinova** [SteamDatabase/steamdb.info-issues#717]
### Feature Description

The "Products by cost" list of confusing in any other currency than USD because it just looks like a hodgepodge of random values:

| USD | NZD |
|--|--|
 | ![image](https://user-images.githubusercontent.com/42429413/124073229-fe845600-da95-11eb-97d7-5d6921e42f6b.png)| ![image](https://user-images.githubusercontent.com/42429413/124073182-ead8ef80-da95-11eb-8470-fc298e92b734.png) |

Rounded baselines (like 2/5/10 or 200/500/1000 depending on currency) should be used in all currencies, with the number of products in each category depending on what the local currency is instead of being all grouped in USD before currency conversion.

(Sidenote: USD should be US$ instead of just $ and __$ doesnt need a space after)

**Comment by xPaw** [comment]
I changed it to use Valve's pricing matrix, so values should be more reasonable now.
