### ISSUE TITLE
Graphs are broken on Seamonkey

### ISSUE THREAD

**Issue by dilworks** [SteamDatabase/steamdb.info-issues#718]
- _Browser name and version:_ Seamonkey 2.53.8
- _Device (mobile or desktop):_ Desktop (Linux x86_64 PC)
- _Page where the issue happens:_ https://steamdb.info/graph/ (or anything that has charts)

### Describe the bug

Until recently everything worked fine on Seamonkey (and I assume that in every alternative browser that isn't "Chrome" or "latest Firefox"). Today I find broken graphs with endless spinning loading circles and "Initializing chart... You must have JavaScript enabled." for each instance. On the browser JS console, I find the following errors:

> SyntaxError: expected expression, got '.'  global.js:1:6294
> ReferenceError: SteamDB is not defined graphs.js:1:1946
> SyntaxError: bad method definition  searchable-select.js:1:49
> TypeError: window.SteamDB is undefined  hover.js:1:526

The first SyntaxError is due to the use of "t?.postMessage(e.data)", aka the Optional Chaining operator (?.), which is a quite recent addition to the (never ending) evolving standards. No clue on the other ones, as my JavaScript is far from strong.

Yes, I know that the usual answer would be "just install Chrome/latest Firefox, as we only test in those", but for those of us that have very valid reasons to use alternative browsers, it's still a pity that we get sidelined in the chase of shiny features :/

**Comment by xPaw** [comment]
Optional Chaining has been added in Firefox 74, current ESR is 78. SeaMonkey should just keep their fork more up to date.

**Comment by dilworks** [comment]
Can confirm fix. Awesome, you rock~

As for Seamonkey getting up to date... the sad reality applies to all Firefox-derivatives: so much new stuff getting in the standards (mainly pushed by Google), so much code to backport (mostly due to technical limitations), and of course, so little manpower willing to contribute. Still, I'm grateful for the prompt fix, a rarity these days, and thanks for not dismissing my bug report with a stark "use latest Chrome/Firefox", I really appreciate it!
