### ISSUE TITLE
Increase bad price limit for VND

### ISSUE THREAD

**Issue by nhahtdh** [SteamDatabase/steamdb.info-issues#719]
- _Browser name and version:_ Any
- _Device (mobile or desktop):_ Any
- _Page where the issue happens:_

  - https://steamdb.info/app/*/
  - https://steamdb.info/sales/

### Describe the bug

Currently, the prices of the products in VND are not shown in the regional prices listing of an app when the number is above certain limits (probably around 1 million VND ~ around 43 USD).

For example, [NieR Replicant ver.1.22474487139...](https://steamdb.info/app/1113560/) prices for VND shows up blank in the app while the prices are [shown properly in the sub](https://steamdb.info/sub/502733/)

This limit is way too low and should be raised to at least 100 million VND (around 4300 USD) or 1 billion VND (43000 USD)

**Comment by xPaw** [comment]
That's not a bug with limit, but Steam store not correctly showing the price metadata for VN for some reason, so steamdb does not see that as having a price.
