### ISSUE TITLE
Add Steam Support link

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/steamdb.info-issues#723]
### Feature Description

It would be nice to see a Steam Help button here:
![image](https://user-images.githubusercontent.com/4411977/130525765-3b398775-f893-4ebb-b638-5e545ab0c80d.png)

**Comment by xPaw** [comment]
Don't really see a need for one, how often do you need to visit support?

**Comment by Revadike** [comment]
> Don't really see a need for one, how often do you need to visit support?

i guess only to remove/restore packages. :P 
maybe add a button for that?
