### ISSUE TITLE
Instant Search - Add Review Count slider

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/steamdb.info-issues#728]
### Feature Description

The number of reviews is helpful to indicate the popularity of a game and can indicate somewhat of how many owners it has, so having the ability to limit this can help fine tune our searches. Personally, I would use to it to find popular games. Top ingame player games list doesn't work as those are mostly multiplayer games and only work for a certain moment in time.

**Comment by sirsnowy7** [comment]
Bump. Would like to use this to find less played games
