### ISSUE TITLE
Players Trend on graph is broken

### ISSUE THREAD

**Issue by def-** [SteamDatabase/steamdb.info-issues#731]
- _Browser name and version:_ Firefox 92
- _Device (mobile or desktop):_ Desktop
- _Page where the issue happens:_ https://steamdb.info/app/412220/graphs/

### Describe the bug
Players Trend on graph is broken since the switch to hourly player statistics (compared to the old 10 min interval). The line does not correspond to the actual player statistics.

**Comment by xPaw** [comment]
Fixed.

You can login to see the higher density data as before.
