### ISSUE TITLE
Add Link to Official News RSS Feeds

### ISSUE THREAD

**Issue by xM8WVqaG** [SteamDatabase/steamdb.info-issues#732]
### Feature Description

Valve publishes RSS feeds of the News section for games. 

For example, the SteamDeck:

SteamDB: https://steamdb.info/app/1675180/
Steam Official Group: https://steamcommunity.com/games/1675180
Steam News RSS Feed: https://steamcommunity.com/games/1675180/rss/

This RSS feed is generated for all games I tested. Note, it is under the official group name rather than the App ID. This is important as the official group for some older Valve games is not the App ID.

For example, CounterStrike Source:

SteamDB: https://steamdb.info/app/240/
Steam Official Group: https://steamcommunity.com/games/CSS
Steam News RSS Feed: https://steamcommunity.com/games/CSS/rss/

It would be convenient if SteamDB had a link to the official RSS feed rather than having to manually assemble it myself.

**Comment by xPaw** [comment]
You can just use `https://steamcommunity.com/ogg/730/rss/` which will redirect you to the relevant vanity url if needed.
