### ISSUE TITLE
Light mode toggle disappeared

### ISSUE THREAD

**Issue by kazerniel** [SteamDatabase/steamdb.info-issues#733]
- _Browser name and version:_ Firefox 94.0.1
- _Device (mobile or desktop):_ desktop
- _Page where the issue happens:_ any app page

### Describe the bug

There used to be a toggle in the footer to switch the site between light and dark mode even after dark mode became default. Now the toggle seems to be gone altogether. Is there a way to view the site in light mode?

**Comment by xPaw** [comment]
I removed it because I don't want to maintain separate versions.
