### ISSUE TITLE
Detection of DLC in library

### ISSUE THREAD

**Issue by AlphaScorpii-dev** [SteamDatabase/steamdb.info-issues#735]
I don't know if it's a bug on my side, or a feature missing, but as far as I can tell, no DLC is detected in my library.
As a consequence, the filter to hide owned items only works for games, and leaves all DLC displayed.
In case it's a limitation of the Steam API, perhaps a workaround would be to let us import a list of our owned contents (using a copy/paste from [userdata](https://store.steampowered.com/dynamicstore/userdata/) comes to my mind).
This way, we could easily filter to query only missing DLC from games we own (right now, I get the whole list of DLC, including the ones I already have, so this is not really efficient).

**Comment by xPaw** [comment]
Install the extension, it does exactly this.
