### ISSUE TITLE
Thumbnails are not loaded until the page stops scrolling

### ISSUE THREAD

**Issue by duckyb** [SteamDatabase/steamdb.info-issues#736]
- _Browser name and version:_ Chrome v96
- _Device (mobile or desktop):_ Windows 10 Desktop
- _Page where the issue happens:_ Sales Page

### Describe the bug
While scrolling the list of games, the thumbnails don't load unless the page stops scrolling.

### How to reproduce
Go on the sales page, click the middle mouse button to enter scrolling mode and start slowly scrolling the list.

### Expected behaviour
The thumbnails should load when the item enters the view.

### What happens
The thumbnail doesn't load, the default steam thumbnail is used instead.

### Additional info
![steamdb](https://user-images.githubusercontent.com/27895007/143838396-8679dac3-19be-49f7-b739-2b0560a984e4.gif)

**Comment by xPaw** [comment]
There's a 100ms delay as a performance optimization.

**Comment by duckyb** [comment]
> There's a 100ms delay as a performance optimization.

I don't believe this has to do with the issue.
The thumbnails won't load if you keep scrolling, no matter how long you wait.

**Comment by xPaw** [comment]
It is, the 100ms timeout resets if a new scroll event is triggered.

**Comment by duckyb** [comment]
> It is, the 100ms timeout resets if a new scroll event is triggered.

Makes sense.
Maybe the timer could be changed to "item stays for 100ms into view" instead of "check after 100ms of not scrolling"?
