### ISSUE TITLE
Instant Search: Engine.Adobe AIR gets no results

### ISSUE THREAD

**Issue by ToughGuyKunio** [SteamDatabase/steamdb.info-issues#737]
- _Browser name and version:_ Firefox 95.0 & Vivaldi 5.0.2497.30
- _Device (mobile or desktop):_ Deskotp
- _Page where the issue happens:_ https://steamdb.info/instantsearch/?refinementList%5Btechnologies%5D%5B0%5D=Engine.Adobe+AIR

### Describe the bug

**Behavior:**
1. go to https://steamdb.info/tech/
2. click "Adobe Air"
3. click "Filter in Instant Search"
4. Get error message: "No results found in 1ms"

**Expected behavior:**
1. go to https://steamdb.info/tech/
2. click "Adobe Air"
3. click "Filter in Instant Search"
4. Get results.

**Comment by xPaw** [comment]
It didn't encode the link correctly, you can select it from Technologies on the left.

Will fix though.
