### ISSUE TITLE
Minimum and maximum number of (online) co-op players in Instant Search

### ISSUE THREAD

**Issue by andrasfuchs** [SteamDatabase/steamdb.info-issues#739]
First of all SteamDB and its instant search are absolutely amazing!

There is only one parameter I miss. I have a small group of gamer friends who play together on a regular basis. We usually play 2 or 3 hours per occasion, and there are typically 5 of us present. One of the challenges we have is that we don't really know what games are out there that support 5 players in a online co-op setting. 

So, it would be great if [SteamDB Instant Search](https://steamdb.info/instantsearch/) had this filter in a similar fashion as it has the SteamDB rating, so as a user I could filter the games that support online co-op for let's say 5-8 players.

![image](https://user-images.githubusercontent.com/910321/146546302-96662d45-d648-47a6-88cc-57237ac1010b.png)

This information is not available on Steam by default as far as I know, but sites like [co-optimus.com](https://www.co-optimus.com/game/3480/pc/tom-clancy-s-rainbow-six-siege.html) has these. 
![image](https://user-images.githubusercontent.com/910321/146546683-721b62a5-deab-427a-8066-01d095e24120.png)

If there was a way to upload these datapoints manually I could personally contribute some time to it and help SteamDB grow in this way.

Update: I talked to the guys at co-optimus.com and they made their API available for use. This way it's now possible to request multiplayer information programmatically. For example if we are interested in the Steam game with the application id of `359550`, we can call http://api.co-optimus.com/games.php?search=true&steam=359550 and get back a game object.

![image](https://user-images.githubusercontent.com/910321/146678430-5dad8008-837e-483d-b09c-18e270e2515f.png)

The relevant information for this feature request is the `online` property of the returned `game` object.

**Comment by xPaw** [comment]
This would require pulling data from a third party as you say (with questionable quality), so no plans to add this.
