### ISSUE TITLE
Import Wishlist from steam (Augmented Steam) to Steamdb Watch list

### ISSUE THREAD

**Issue by MohandL3G** [SteamDatabase/steamdb.info-issues#744]
You can Export your Steam wishlist using something like Augmented Steam or maybe even Enhanced Steam to a text or json file.

Can you add a way to import this file to Steamdb Watch list.

Sorry for bad english, and thanks in advance.

**Comment by xPaw** [comment]
Use the steamdb extension.

**Comment by MohandL3G** [comment]
I have steamdb extension installed, I tried to search and search for it and I couldn't do it, thank anyway.

**Comment by xPaw** [comment]
SteamDB extension actually highlights stuff on steamdb pages without having to import anything manually, as long as you are logged into the Steam store.

**Comment by MohandL3G** [comment]
Yes I know, but I want to import the Wishlist to Watch list, I have to do it manually, and I have more than 430 game on my Steam Wishlist.

SteamDB Watch list is far better than Steam Wishlist imo.

And I want to import my Wishlist to SteamDB.

**Comment by xPaw** [comment]
Oh right I completely missed that you wanted it in the watch list. Yeah sorry that's not a thing.

**Comment by MohandL3G** [comment]
No prblem, thanks for the help, i guess I'll add manually one by one.

**Comment by chinarut** [comment]
> not really designed to be used for the wishlist

could you elaborate on this more?  what is steamdb more intended to be used for?

it would be absolutely awesome to skip importing all together and but just simply see a view of my wishlist in steamdb!

**Comment by xPaw** [comment]
You can.

![image](https://github.com/user-attachments/assets/713d1ffe-aaeb-4018-8be5-8ae922ddb870)

**Comment by chinarut** [comment]
oh sorry about that - I just found it!  awesome! 👾

https://steamdb.info/sales/?displayOnly=Wishlist
