### ISSUE TITLE
Found a minor typo: on Search sign-in page

### ISSUE THREAD

**Issue by morgzz** [SteamDatabase/steamdb.info-issues#745]
- _Browser name and version:_ Firefox 97.0.1 (64-bit)
- _Device (mobile or desktop):_  Desktop
- _Page where the issue happens:_ Listed below

### Describe the bug

Found the issue on the following page route:
https://steamdb.info/search/?a=app_keynames&type=-1&keyname=530&operator=1&keyvalue=

We use cookies to keep _your_ signed in session active.

**Suggested solution**
replace with  `you`  or
`We utilize cookies to remember your active session.`

**Screenshot**

![image](https://user-images.githubusercontent.com/880477/155875454-0878abed-8221-44c3-9234-1ae8ce15b650.png)

**Comment by xPaw** [comment]
The session is yours, that's not a typo.
