### ISSUE TITLE
Release dates filters are inconsistent

### ISSUE THREAD

**Issue by the-overdriven** [SteamDatabase/steamdb.info-issues#748]
- _Browser name and version:_ 
Newest Chrome Version 99.0.4844.82 (Official Build) (64-bit)
- _Device (mobile or desktop):_ 
Desktop
- _Page where the issue happens:_ https://steamdb.info/instantsearch/?refinementList%5BreleaseYear%5D%5B0%5D=2002 (it should show Dungeon Siege in the list and all other games that were released in 2002)

### Describe the bug
On [instant search](https://steamdb.info/instantsearch/) Release Year filter is inconsistent.
For some games it's looking at year when it was added to store (i.e. Dungeon Siege released in 2002 will be under 2011, because that's the year when it was added to store). Meanwhile for other games, i.e. Worms Armageddon will be correctly under year 1999 (Store Release Date), while it was added to store in year 2013 (Store API Release Date). Two games, completely different filtering logic. Not only it's impractical, it's also inconsinstent and confusing.

As a result Release Year filter is rather useless as it's showing very few games:
![image](https://user-images.githubusercontent.com/100090726/160293141-21ba5654-cd4a-442c-9ea1-6b7a6b47a3dc.png)

Solution: **Year filter should look only at Store Release Date**. What do we care about year when game was added to Steam? Date of releasing the game is more important.

steamdb.info (**incorrect** release date, this date is used by [instant search](https://steamdb.info/instantsearch/))
![image](https://user-images.githubusercontent.com/100090726/160292908-a8b846bc-5aed-4332-aa27-d60a1d84817c.png)

Store (**correct** release date)
![image](https://user-images.githubusercontent.com/100090726/160292920-f18f3499-7e2d-4c88-a381-1174493d471a.png)

example of **correct** release date at steamdb.info
![image](https://user-images.githubusercontent.com/100090726/160293034-4d13620c-97d1-485d-9b18-f7effcb7e336.png)

**Comment by xPaw** [comment]
It uses `common_steam_release_date` by default, and falls back to `website_release_date` field if that is missing (which it is on Worms), it's inherently inconsistent due to the Steam data.

**Comment by the-overdriven** [comment]
@xPaw Can we invert it then?
I mean use `website_release_date` by default, and fall back to `common_steam_release_date` field if `website_release_date` is missing.

**Comment by xPaw** [comment]
That doesn't solve the problem.

**Comment by the-overdriven** [comment]
Maybe, but perhaps it will make year filter less broken and actually useful.

**Comment by the-overdriven** [comment]
@xPaw Somehow, they do it correctly at https://www.lorenzostanco.com/lab/steam/store/ despite "inherently inconsistent Steam data"
![image](https://user-images.githubusercontent.com/100090726/160295025-e6fb6a3b-488f-44e7-974c-8868098c793a.png)
Notice "more than 60 games found", whereas steamdb.info finds only 6 games in 2002.
