### ISSUE TITLE
Browser crashes when opening page

### ISSUE THREAD

**Issue by Zoobdude** [SteamDatabase/steamdb.info-issues#754]
Chrome and Opera GX on Xiaomi Mi 11 lite 5g
Mobile
[https://steamdb.info/depot/731/history/](https://steamdb.info/depot/731/history/)

When opening the above web page my browser freezes and only the first part of the web page is loaded but the history is not.

Other addresses like:

https://steamdb.info/depot/732/history/
https://steamdb.info/depot/733/history/
https://steamdb.info/depot/734/history/
https://steamdb.info/depot/735/history/

Seem to work fine (there're a couple of performance issues now and again) but mostly it's pretty reasonable.

I assumed it was because my soc was not strong enough (it's got a Snapdragon 780G).

**Comment by xPaw** [comment]
This seems like some kind of Chrome issue, I can repro it in Chrome on Android as well. I tried to profile the page, but I don't see any obvious hiccups.

Can you report it on https://bugs.chromium.org/p/chromium/issues/list ?
