### ISSUE TITLE
SteamDB seems to not show list of changed files for new patches

### ISSUE THREAD

**Issue by kolardavid** [SteamDatabase/steamdb.info-issues#756]
In "Patches" section of the app, for earlier updates, SteamDB always shows list of modified files inside depots - for example here:
https://steamdb.info/patchnotes/8964922/

Roughly around 21st July, this is no longer the case - only changenumbers are shown - see here:

Train Sim World 2:
https://steamdb.info/patchnotes/9000099/
https://steamdb.info/patchnotes/9060073/
https://steamdb.info/patchnotes/9101402/

House Party:
https://steamdb.info/patchnotes/9131790/

Police Simulator - Patrol Officers:
https://steamdb.info/patchnotes/9107010/

... and most probably all patches for any game after July 21st.

**Comment by xPaw** [comment]
There's a banner there that says why.
