### ISSUE TITLE
Allow AND/OR-searches for multiple tags

### ISSUE THREAD

**Issue by tdnzr** [SteamDatabase/steamdb.info-issues#757]
When I search SteamDB for multiple tags, I can currently only do an AND-search, e.g. Roguelite AND Roguelike, not Roguelite AND/OR Roguelike. It would be helpful to be able to do AND/OR searches, as well.

Example use case for an AND/OR search: suppose I'm a Roguelike afficionado and want to search for games with aspects of roguelikes, permadeath, exploration, or similar. Unfortunately, Steam spreads that info out over many tags, so I'd need an AND/OR search for tags like these: Roguelite, Roguelike, Action Roguelike, Perma Death, Metroidvania, Souls-like, Traditional Roguelike, Roguevania.

(One service I'm aware of which allows AND/OR searches is Steam250 ([here's](https://club.steam250.com/ranking/custom/AJjOAA4Tw84ABu4rzac0zXMqzQ93zQbfzQa0zQZckAAAoQE) the aforementioned search for all these roguelike tags), but their search otherwise lacks important features like searching for discounts or hiding games in one's library.)

**Comment by xPaw** [comment]
On which page?

**Comment by tdnzr** [comment]
Ah, I meant the search feature and its tag filtering on [this page](https://steamdb.info/sales/). Quote from the tooltip: "If multiple tags are included, all of them have to match".

Consider [this example search](https://steamdb.info/sales/?min_reviews=0&min_rating=0&min_discount=0&tagid=42804%2C454187): there seem to be ~10 Traditional Roguelikes and ~138 Action Roguelikes. When I search for both tags via SteamDB, it displays games which have both tags (i.e. 2 games). The AND/OR search I want would find games with either tag and display ~146 games (138+10 minus the 2 games which have both tags).

**Comment by xPaw** [comment]
![image](https://user-images.githubusercontent.com/613331/180858173-e83ea976-e052-4551-adcf-f33dd7f1ef3a.png)

**Comment by tdnzr** [comment]
Thanks a ton for this update! As a very tiny issue, due to this update, the tag search tooltip is no longer up-to-date:
![firefox_2022-07-26_21-22-52](https://user-images.githubusercontent.com/35105157/181094607-ce5ea5f7-2911-40a8-9ddd-82086f373775.png)
