### ISSUE TITLE
Track depot app reference changes and few other impovements(?)

### ISSUE THREAD

**Issue by nisehime** [SteamDatabase/steamdb.info-issues#759]
### Feature Description

Sometimes you stumble across depots that don't have app references but they did have them historically. That's a bit confusing. Can steamdb track app reference changes for depots like it does it with packages?

Also, I found this depot: 1523211. On its page you can only see package reference changes, however if you open any app that references this depot (1030830 for example), you can see manifest id changes for this depot too, which is not reflected on the depot's page. Neither it displays all apps that reference this depot for some reason.
Could it be because your bot doesn't own the base app of this depot? If it is so I think you can pick any random app that references it (preferably those your bot own to see file changes) and track manifest changes using it. Since it's a shared depot, as I understand it, I suppose there souldn't be any problems, the manifest changes would be equal to all apps right?

**Comment by xPaw** [comment]
> If it is so I think you can pick any random app that references it

It's way trickier to do than it sounds.

> Since it's a shared depot, as I understand it, I suppose there souldn't be any problems, the manifest changes would be equal to all apps right?

Nope, this isn't true, and the primary reason why I only track depot changes from the parent app.

**Comment by nisehime** [comment]
> Nope, this isn't true, and the primary reason why I only track depot changes from the parent app.

I see. Is this also the reason it doesn't show connected apps?

**Comment by nisehime** [comment]
What about tracking app changes?
