### ISSUE TITLE
Free Packages pages issues

### ISSUE THREAD

**Issue by Nuklon** [SteamDatabase/steamdb.info-issues#760]
- _Browser name and version:_  Firefox 104, but it doesn't matter
- _Device (mobile or desktop):_  Desktop
- _Page where the issue happens:_ https://steamdb.info/freepackages/#

### Describe the bug
There are two problems on the Free Packages page, I'll list them.
- Free Weekend packages are listed and cannot be added, example: https://steamdb.info/sub/751654/ (this fails PurchaseResultDetail=5)
- Some outdated packages are listed and can no longer be added, examples: https://steamdb.info/sub/641116/ https://steamdb.info/sub/612035/ I think freepackages should only list packages it can confirm that can still be added.

**Comment by xPaw** [comment]
1. That's a limitation of how free weekends work, Steam doesn't say that you own them hence they don't get hidden (they will disappear when it expires)
2. These packages were not updated to have unavailable state. You can use the hide button, it's there for such reasons.

**Comment by Nuklon** [comment]
Can't you hide free weekends then? It seems this is already known: FreeWeekend: Yes :) I will ignore the others.
