### ISSUE TITLE
Can't access SteamDB due to Cloudflare

### ISSUE THREAD

**Issue by EvgenKo423** [SteamDatabase/steamdb.info-issues#762]
- _Browser name and version:_ Vivaldi 3.3 / Chrome 85
- _Device (mobile or desktop):_ Desktop
- _Page where the issue happens:_ All

### Describe the bug

Since somewhere in July this year, I guess, I can no longer access SteamDB. The page keeps refreshing no matter how many capchas someone solves. Yes, I see it says:

> SteamDB requires a fully up to date browser. 

but then it also says:

> As a reminder, SteamDB is a hobby project that makes no money.

This is ridiculous. If SteamDB is a hobby project, then what's the point to force people to use a fully up to date browser (or use features that cause so, for that matter)? Why can't you sacrifice some uptime for site accessibility, does someone actually DDoS you, why not activate the DDoS protection when it actually becomes necessary?

People may have their own reasons to not update. While you try to get a 100% uptime for some people, you actually getting a 100% downtime for the others. Please fix this madness (or the brains of Cloudflare devs).

**Comment by xPaw** [comment]
There's just a challenge for older browsers, if it keeps refreshing for you that means you're likely somehow breaking it with some setting or extension.

If you are unable to bypass the challenge, feel free to report a bug to Cloudflare.

> If SteamDB is a hobby project, then what's the point to force people to use a fully up to date browser (or use features that cause so, for that matter)?

Because I am free to do so.
