### ISSUE TITLE
Regional differences for bundles?

### ISSUE THREAD

**Issue by nisehime** [SteamDatabase/steamdb.info-issues#764]
### Feature Description

Bundles can contain different packages for various regions. Example: https://steamdb.info/bundle/7163/
The japanese region has subID 209639 for Wolfenstein.

I wanted to report it as a bug actually, but not sure if it's not because API is not providing this info in one call.

**Comment by nisehime** [comment]
In fact, I believe there's no regional differences in the bundles themselves, they just include all packages and then they're automatically excluded during purchase if not available in some region. I don't know how steamdb gets price info for all currencies, but if it just switches between different country codes (like `?cc=`) then missing packages in bundles might be a bug.

**Comment by nisehime** [comment]
The short description on packages should be better based on set price. For example on Wolfenstein bundle there's two packages that say "not in SA", which is not really important, what is important is that the price on sub 183398 is only set in Switzerland, so it's only available there

**Comment by xPaw** [comment]
I know, it's displaying the actual restrictions not where the price is set (which in this case displays no price for you based on your currency).

I'll look into displaying restricted packages separately later.

**Comment by nisehime** [comment]
That is what I'm saying. The sub 183398 is saying that it is restricted in Saudi Arabia, but the point is that it has the price set only in Switzerland, so it's only available in Switzerland from Steam store. "Not in SA" description in this case is not useful and makes it look like a dup of sub 164072, which also just says "not in SA", even though it is in fact also not available in Russia, Japan, Switzerland, Qatar etc. Description based on prices included/excluded makes more sense.
