### ISSUE TITLE
429 Too Many Requests for price history

### ISSUE THREAD

**Issue by real-yfprojects** [SteamDatabase/steamdb.info-issues#766]
- _Browser name and version:_ Firefox 107
- _Device (mobile or desktop):_ desktop
- _Page where the issue happens:_ every game page `https://steamdb.info/app/*/`

### Describe the bug

The price history doesn't load for any game. Instead the frame displays the text `⚠ Sorry, failed to load price history: ServerError: Please do not scrape. SteamDB is a community project that does not make money. See FAQ: https://steamdb.info/faq/#how-are-we-getting-this-information`. However this is definitely not a problem of me making to many site requests.

I found the following error in the developer console:

```
GET https://steamdb.info/api/GetPriceHistory/?appid=730&cc=eu
[HTTP/3 429 Too Many Requests 122ms]
```

**Comment by xPaw** [comment]
Chances are you modified some Firefox setting that breaks it. I suggest trying a clean profile or another browser.

**Comment by hellotinh03** [comment]
For future visitors, try reverting the "network.http.referer.spoofSource" in your about:config.
