### ISSUE TITLE
Add a way to change logo position in game mode and a new filter

### ISSUE THREAD

**Issue by Free0Bird** [SteamDatabase/steamdb.info-issues#769]
### Feature Description

Title. Just have a way to change where it is. Either by having set locations (such as left side, center, and right side) or by allowing you to manually change it's position. Adding onto that, a nice filter feature would be to see specific things that have a "bias" to one side or the other. It would go well with the new change in icon placement if you could find specific images like that.

**Comment by xPaw** [comment]
I have no idea what youre talking about but steamdb has no game mode.
