### ISSUE TITLE
"Is your clock out of sync?" even with correct time

### ISSUE THREAD

**Issue by Velken** [SteamDatabase/steamdb.info-issues#770]
- _Browser name and version:_  Firefox 108.0.2 (64bit)
- _Device (mobile or desktop):_ Windows 10 22H2 19045.2364
- _Page where the issue happens:_ https://steamdb.info/sales/history/

### Describe the bug

I keep getting the pop-up for "Is your clock out of sync?" on the sales history page
My computer time is synced with NTP pool, but according to "time.is" it is +/- 10-30 seconds off, but not according to NTP pool

Could the popup be changed to only show if the different is greater than 1 minutes? or at least let me "never show this again"

**Comment by xPaw** [comment]
10-30 seconds is a lot.

**Comment by Velken** [comment]
> 10-30 seconds is a lot.

ok, but either NTP is wrong or time.is is wrong

i just want the message gone from my screen

**Comment by 9021007** [comment]
![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/24487638/8dce81c3-96f6-4ca6-aa99-ed29954098ff)
![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/24487638/1e79ddbe-2846-4b09-9a8f-2b16f22f73f4)
time.is and SteamDB seriously disagree on the time. Is the SteamDB server having issues?
