### ISSUE TITLE
CPU maxing out when visiting site

### ISSUE THREAD

**Issue by QazCetelic** [SteamDatabase/steamdb.info-issues#772]
- _Browser name and version:_ Firefox 109.0 (64-bit)
- _Device (mobile or desktop):_  Desktop
- _Page where the issue happens:_ https://steamdb.info/freepackages/

### Describe the bug
![image](https://user-images.githubusercontent.com/51381523/215984998-7281d323-750e-4e52-8ba0-3260200fa0e5.png)
Site becomes completely unresponsive.

Firefox profiling: https://share.firefox.dev/3X96iy5

![image](https://user-images.githubusercontent.com/51381523/215985394-e3909dfe-5b8c-4e29-8176-71d8339cb846.png)

![image](https://user-images.githubusercontent.com/51381523/215985510-11e459ad-87fd-4e6c-966c-c3cbb385f0cd.png)

**Comment by xPaw** [comment]
I don't see an issue with anything related to SteamDB code in that profile, nor can I repro it in Firefox. If you think the issue is SteamDB's code, please point out which code it is, because I can't see it.

I suggest you test a clean Firefox profile with default settings and no other addons.
