### ISSUE TITLE
Some discounts ending earlier than the time suggested by the Sales page

### ISSUE THREAD

**Issue by enchained** [SteamDatabase/steamdb.info-issues#773]
I encountered this multiple times during the last few months. The latest example is ChromaGun. I always sort the sales page by Ends in to see which sales ending in the next 24h, and ChromaGun definitely wasn't on top of the sorted table when I checked 12 hours earlier. Which means it was supposed to end along with most other discounts at 18:00 UTC. But the discount was already gone at 13:15 UTC (both from Steam and SteamDB). 

I also experienced some discounts having a different Ends in counter on Steam than on SteamDB, but didn't have the time to report it.

How often does SteamDB sales page fetches its Ends in counters? Is it only once on the start of the discount? Could it be that some publishers adjust the times later? Could additional timer refreshes be added at 24h/12h/6h before the supposed end of the discount?

Other thing I noticed is sometimes when I sort the Sales table by Ends in, it can mix in some different timers in between, and usually the difference is 1 hour at most (like 15h, 15h, 15h, 14h, 15h etc). I also often use secondary sorting by reviews (by holding Shift), but it should not affect the primary sorting order normally.

**Comment by xPaw** [comment]
It's not impossible to have wrong end times, sometimes Steam even keeps discounts for days after the end time, and the Steam page just displays "ends in" with no actual time. SteamDB certainly updates more than "start of the discount".

As for sorting, it works fine for me. Sort by end time, then hold shift to sort by rating.

**Comment by enchained** [comment]
> It's not impossible to have wrong end times, sometimes Steam even keeps discounts for days after the end time, and the Steam page just displays "ends in" with no actual time. 

Is this why Trails of the Black Sun is still on the SteamDB sales page with Ends in —? Cause it already ended on Steam, and [Google cache](https://webcache.googleusercontent.com/search?q=cache:glAs7uPJn50J:https://store.steampowered.com/app/1152940/Trails_of_the_Black_Sun/) timer from yesterday (19th Feb at 04:24:28 UTC) suggests it was to be ended today at 12:00 UTC. Did SteamDB crawler somehow not see it, or it means that the timer wasn't there yet at the last sync time?

I was always wondering what was the cause of games still hanging there. Either way, such cases are harmless, while potentially missing a discount ending early can be a bit upsetting and requires to manually re-check everything that is ending soon.

> SteamDB certainly updates more than "start of the discount".

Is there a specific interval set? Would you mind if I'll report cases when times are different between SteamDB and Steam, if I encounter them in the future? But without knowing the approximate interval, I wouldn't know whether such cases are "not yet synced" or an actual bug, and also knowing the interval would help to know how often should I re-check timers manually.

> As for sorting, it works fine for me. Sort by end time, then hold shift to sort by rating.

That's what I do, but I think it reproduces only for specific games or something. I just mentioned it in case it was a known issue. I'll try to post it next time it is reproduceable.

**Comment by xPaw** [comment]
There's 250k apps on Steam, it's impossible to keep them all updated "live" for such a minor thing as sale ending date changing unexpectedly.
