### ISSUE TITLE
[SteamTracking] Tracking www.counter-strike.net

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamdb.info-issues#779]
### Feature Description

[www.counter-strike.net](https://www.counter-strike.net/) has been updated and replaced with the same architecture as [www.dota2.com](https://www.dota2.com/).

example: https://www.counter-strike.net/public/css/csgo_react/main.css

**Comment by xPaw** [comment]
Isn't it tracked already?

**Comment by wordlesswind** [comment]
oh sorry, I can't believe I didn't notice that.
