### ISSUE TITLE
Free Package link issues

### ISSUE THREAD

**Issue by jjjjj8797** [SteamDatabase/steamdb.info-issues#782]
- _Browser name and version:_ Chrome Version 114.0.5735.134 (Official Build) (64-bit) 
- _Device (mobile or desktop):_ Desktop, windows 10
- _Page where the issue happens:_ https://steamdb.info/sub/......

### When I scroll through https://steamdb.info/freepackages/# and open any package, none of the buttons work except for **watch**. **Add Free License** gives me this "_Something went wrong. There was a problem adding this product to your account._", **Install** takes around 30 seconds before steam shows this error "_An error occurred while installing AppID 0: “connection time out”_", and **Store** takes me to Steam's home page. But if I go the **Apps** tab and click on the **APPID**, I can then use the **Install** button to download the demo on steam, but the issue is that, for some of the packages, you actually have to use the **Add Free License** button from the Free Packages page for it to work.

**Comment by xPaw** [comment]
The add free license was broken because Valve moved checkout, there was an extension update to fix it, but the Steam store has a bug with sessionids (affects store itself too).

As to install button not working, that's just Steam client.

**Comment by hacknug** [comment]
Is this supposed to work? I can't activate free packages as I used to regardless of method (SteamDB, ASF, or Steam Console). I guess the issue was closed because there nothing we can do until Valve fixes the sessionids issue mentioned?

**Comment by xPaw** [comment]
Let's keep it here: https://github.com/SteamDatabase/BrowserExtension/issues/145
