### ISSUE TITLE
"Average price per hour" in calculator misleading

### ISSUE THREAD

**Issue by uthbees** [SteamDatabase/steamdb.info-issues#783]
### The problem
The "Average price per hour" field at https://steamdb.info/calculator uses the formula:
`sum_over_all_games(price_of_game_X/hours_in_game_X)/count_of_games`
instead of the formula that (in my opinion) it should be using:
`total_price/total_hours`

### Why this is a problem
There have been several issues over the years for the "Average price per hour" field (see #362, #403, and #703). In these issues, it has been made clear that the current behavior is intended. However, I think it's clear that this behavior, in its current implementation, is misleading - if the mentioned issues and my own experience aren't enough, a quick google search also brings up:
- [This confused post](https://forum.level1techs.com/t/apparently-steam-has-a-new-tool-that-shows-you-how-much-youve-spent-on-your-account/128556/65) (with the next one agreeing "no idea").
- [This reddit thread](https://www.reddit.com/r/patientgamers/comments/1s2zyg/what_is_your_costhour_for_your_steam_collection/) with multiple [comments](https://www.reddit.com/r/patientgamers/comments/1s2zyg/comment/cdtnk3k) listing data that shows that the "overall cost per hour" from [gaugepowered.com](https://i.imgur.com/6ufKhMg.jpg) (now dead) used the simpler formula. No one is confused. Note also that [it appears](https://github.com/SteamDatabase/steamdb.info-issues/issues/353) that gaugepowered.com was the inspiration for this feature, so the current behavior may actually have originally been a mistake.
- [This reddit thread](https://www.reddit.com/r/Steam/comments/vxoqou/whats_your_cost_per_hour_mine_is_kinda_sad_site/) with [this comment](https://www.reddit.com/r/Steam/comments/vxoqou/comment/ify5z3r/) giving an explicit (wrong for steamdb! the user uses the second formula, not the first) explanation of what "Average price per hour" means, [this comment](https://www.reddit.com/r/Steam/comments/vxoqou/comment/ifxrp7u/) *correctly* mentioning that the calculator is not accurate for them, [this comment](https://www.reddit.com/r/Steam/comments/vxoqou/comment/ifx8zyn) saying that "their $8 per hour is kind of sad" (first formula), then comparing the number to a manual calculation using the second formula (they come out with 36 cents, but don't notice the discrepancy) if they bought everything at lowest price, and at least like three more comments in the same vein. I didn't see anyone mentioning the formula that's actually used.

I'm sure I could find more evidence, but that seems like enough.

I also argue that the current behavior isn't very useful, even if you do understand it. I can kind of see how it means... something, but it's really hard to wrap my brain around what it actually represents, even knowing the formula. On the other hand, a simple overall average is easy to think about and draw conclusions from: "Whenever I sat down to play games from my Steam library, I was effectively paying X dollars for every hour of overall entertainment."

### Solutions
Based on the evidence, I think it's clear that the formula should be changed from the first formula I mentioned to the second one. (Of course, I'm certainly open to the possibility that I missed a reason why the second formula is better.)

Regardless of whether the formula is changed, though, I think the description/tooltip should be changed as well. If the formula is changed, it should be made clear to users that it's been changed, and that there used to be a different formula in the same spot. And if the formula is not changed, it should be made explicitly clear what the actual formula is, to at least stop the confusion.

(Note: I'm not sure this should be classified as a bug, but being an existing problem rather than something new, I would say it's closer to a bug than a feature request. 🤷‍♂️)

**Comment by xPaw** [comment]
Used this as an opportunity to calculate more stats. Does this match what you would expect now?

![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/613331/9183ca2d-a485-4aa2-b300-407764affc41)

**Comment by uthbees** [comment]
Thanks for the quick response! Yeah, I think that takes care of the big issue. I like the extra new statistics!

Following up, here are my thoughts on a few other things that could potentially be improved:
- It looks like the average price formulas use the lowest prices for your games, whereas the old formula used the current prices. This could be made more clear (maybe in a tooltip?).
- In a similar vein, it might be useful to be able to see the average(s) using today's prices as well. For example, it could say something like "All games: $1.23 - $4.56". (This might not be useful at all, I haven't really thought it through - more just throwing the idea out there.)
- I still think it would be good to be clear that the formula was changed, since there's now a completely different number under the same label. This could be something as little as adding another line to the tooltip saying something like "This formula was changed on June 23, 2023." People who check the page semi-regularly might easily get confused by why their average price per hour suddenly changed, but this extra line would clear up the confusion, at least for most of them.

But these are both more arguable and less important than the main issue was.

**Comment by xPaw** [comment]
I don't really want to use today's prices because they fluctuate, and people then ask why it's lower during big sales.
