### ISSUE TITLE
App Key Search incomplete results

### ISSUE THREAD

**Issue by MichaelHinrichs** [SteamDatabase/steamdb.info-issues#784]
- _Browser name and version:_ Google Chrome
- _Device (mobile or desktop):_ desktop
- _Page where the issue happens:_ https://steamdb.info/search/?a=app_keynames&type=-1&keyname=521&operator=3&keyvalue=Engine.Unreal&all=1

### Describe the bug
Only 37 of 9757 known Unreal Engine apps show up in App Key Search. This happens with search filters for many other engines as well, such as RPGMaker (921 out of 2572), Ren'Py (1,199 out of 2572), and Godot (1,130 out of 809... wait, what???).

**Comment by xPaw** [comment]
Because you didn't use Contains.

But just use this page: https://steamdb.info/tech/Engine/Unreal/?all

**Comment by MichaelHinrichs** [comment]
What's the difference? Also, that page doesn't filter owned games.
