### ISSUE TITLE
Per-platform hours missing

### ISSUE THREAD

**Issue by asdfjkluiop** [SteamDatabase/steamdb.info-issues#785]
- _Browser name and version:_ Librewolf 114.0.2 
- _Device (mobile or desktop):_ desktop
- _Page where the issue happens:_ Calculator page for a user

### Describe the bug
I'm not sure "bug" is the right term as this change might have been intentional. I noticed the per-platform hour table has been replaced with a different one which breaks down hours based on free/paid games. I initially thought this might be due to some steam API change but the API still presents per-platform playtime data. Is there a reason for the removal/could it be added back?

**Comment by xPaw** [comment]
Valve removed it from API.

**Comment by asdfjkluiop** [comment]
They did? I explicitly made a query against my account before opening this issue and it's still there? At least with this endpoint https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/ Is it future removal or was it removed from a different endpoint?

**Comment by asdfjkluiop** [comment]
Huh...you're right...didn't expect that change. Well thanks for the quick response, guess I'll be building my own tool for reporting this on my own account.
