### ISSUE TITLE
Publicly display the 'monthly players breakdown' on app pages

### ISSUE THREAD

**Issue by 07416** [SteamDatabase/steamdb.info-issues#786]
The 'monthly players breakdown' on the app 'charts' pages (`https://steamdb.info/app/*/charts/` now requires logging in via Steam — perhaps most importantly the average monthly player count  isn't shown to all.

I often use SteamDB as a source, I may have to copy the gated information (to a spreadsheet or Markdown table) since most users will not consider logging in... or creating a Steam account if they have none.

example page: https://steamdb.info/app/220/charts/

> Monthly players breakdown  
>Sign in to see a player breakdown per month.

**Comment by xPaw** [comment]
Not at this time.

**Comment by 07416** [comment]
> Not at this time.

@xPaw Any explanation you can share?
