### ISSUE TITLE
Add the ability to turn off the blurring of game search results

### ISSUE THREAD

**Issue by Korb** [SteamDatabase/steamdb.info-issues#788]
There is currently no way to turn off blurring of search results. This is inconvenient because I set the "ignore" status to those games whose pages in the Steam Store I have already seen, as opposed to those games whose pages I have never visited. I can find the same games for different queries, depending on what games I'm looking for. Therefore, it is normal for me when I get the same games in search results for a variety of queries. I would never use the results blur feature. Or, at the very least, I'd like to be able to turn off the blurring that's happening right now.

**Comment by xPaw** [comment]
Since there is a checkbox to hide ignored games, I have removed the blur and added an ignored icon instead (the game is still grayed out though, but it is readable).
