### ISSUE TITLE
Strange download sizes

### ISSUE THREAD

**Issue by nisehime** [SteamDatabase/steamdb.info-issues#795]
- _Browser name and version:_ Firefox 113
- _Device (mobile or desktop):_ Desktop
- _Page where the issue happens:_ https://steamdb.info/app/292120/depots/

### Describe the bug
Not sure if it's a bug on DB side, but as you can see, the download size for both non-shared depots are in terabytes, which I very doubt is accurate.

**Comment by xPaw** [comment]
This is a bug on Steam's end with wrong size in the appinfo, if you click through to the depot it has correct size.
