### ISSUE TITLE
Show links to localized library assets

### ISSUE THREAD

**Issue by nisehime** [SteamDatabase/steamdb.info-issues#798]
### Feature Description

Library assets show that multiple language variants exist, but only one link (to english) is shown. Would be nice if it had links to other languages like with headers and capsules

**Comment by nisehime** [comment]
Just in case localized asset is accessed by adding full language name in the url
Example:
https://cdn.cloudflare.steamstatic.com/steam/apps/2375550/library_600x900.jpg?t=1701948607
https://cdn.cloudflare.steamstatic.com/steam/apps/2375550/library_600x900_japanese.jpg?t=1701948607
https://cdn.cloudflare.steamstatic.com/steam/apps/2375550/library_600x900_tchinese.jpg?t=1701948607
https://cdn.cloudflare.steamstatic.com/steam/apps/2375550/library_600x900_schinese.jpg?t=1701948607
https://cdn.cloudflare.steamstatic.com/steam/apps/2375550/library_600x900_koreana.jpg?t=1701948607

**Comment by nisehime** [comment]
Also, please bring back link to the original sized library capsule
https://cdn.cloudflare.steamstatic.com/steam/apps/2375550/library_600x900_2x.jpg?t=1701948607
https://cdn.cloudflare.steamstatic.com/steam/apps/2375550/library_600x900_japanese_2x.jpg?t=1701948607

It was here before, but since recent changes it now points to half sized generated by Steam

**Comment by xPaw** [comment]
Since Steam added library_assets_full this now works for games that updated their assets. I'm not gonna bruteforce it for apps that don't have it.

https://steamdb.info/app/2796390/info/#assets
