### ISSUE TITLE
It is impossible to pass the captcha

### ISSUE THREAD

**Issue by Korb** [SteamDatabase/steamdb.info-issues#801]
- _Browser name and version:_ Google Chrome 119.0.6045.11
- _Device (mobile or desktop):_ Vivo T1 (4G), Android 13
- _Page where the issue happens:_ https://steamdb.info/upcoming/free/

### Describe the bug
![Screenshot_2023_1013_185947_com chrome beta](https://github.com/SteamDatabase/steamdb.info-issues/assets/3509797/9e38f0ce-565b-4bd1-943e-c133e8c215a4)
(the page reboots infinitely without making it possible to solve the captcha and without giving error messages)

**Comment by hexpwn** [comment]
Are you using VPN?
Possibly related. to [issue 802](https://github.com/SteamDatabase/steamdb.info-issues/issues/802)

**Comment by Korb** [comment]
The problem occurs both with the VPN turned on and off.

**Comment by xPaw** [comment]
Kinda looks like you're using desktop mode in your browser, try disabling that. If that doesn't help, try using a different browser.
