### ISSUE TITLE
Price history is not loading for some reason

### ISSUE THREAD

**Issue by arennf57** [SteamDatabase/steamdb.info-issues#803]
![1698951169168006](https://github.com/SteamDatabase/steamdb.info-issues/assets/68795778/40eef722-dffe-4572-a3e7-b2f951f78488)

Hello, I'm getting this error and have no idea how to fix it...

**Comment by xPaw** [comment]
You can always test a fresh browser profile and a different browser. Some setting in your browser is causing such an issue.
